
[server]
language		= "en"				# server language
languages		= ["fr","en"]

[database]
#type			= "sqlite3"			# uncomment for SQLite
type			= "mariadb"			# uncomment for MySQL internal/server
paths_prefix	= "/home"			# prefix to add to digiKam's AlbumRoot.specificPath to get the real photos folder path

[database.sqlite3]
directory		= "/PATH_TO_SQLITE3_DATABASE"	# directory with .db files
									# when SQLite

[database.mariadb]
connection		= "socket"			# uncomment for MySQL internal
#connection		= "host"			# uncomment for MySQL server
socket          = "/PATH_TO_MARIADB_SOCKET_FILE"	# (mysql.socket)
									# when MySQL internal. can be found with ps -ef | grep digikam
host			= "localhost"		# when MySQL server
user			= "digikam"			# when MySQL server
password		= ""				# when MySQL server

[http]
root_dir		= "../frontend"		# HTML root. may be an absolute path
port			= 4000				# choose prefered port

use_blobs		= true				# use blobs to send binary images date. if false, use base64 encoding (larger)
use_urls		= true				# if true, send url of photos instead of sending their image data
									# set to false if pictures are not on the same server
									# thumbails are always sent as image data
images_root		= "/photos"			# if use_urls, a symbolic link will be made from first dgiKam's AlbumRoot
									# to {root_dir}/{images_root} to allow access from the navigator

thumbnails_limit = 2000				# maximum thumbnails to display, superceedes users limit

force_ssl		= false				# if true, use https
ssl_directory	= "./ssl"


local_trusted	= true				# login without password if source from localhost

[[users]]							# special for login without user/password if local_trusted = true
user			= "local"				
password		= ""
language		= "en"


[[users]]							# normal user from web with full access
user			= "photo"
password		= "photo"
role			= "user"
language		= "fr"

[[users]]							# user from web with limited access
user			= "share"
password		= "share"
language		= "en"
restrict_albums = ["album-1", "album-2"]	# allowed albums
restrict_tags   = ["tags-1","tags-2"]		# allowed tags
