

[fr]
[fr.backend]
	Welcome 			= "Bienvenue à"
	Server 				= "Serveur"
	Database			= "Base de données"
	Unauthorized		= "Commande non permise"
	Forbidden			= "Usager ou mot de passe invalide"
	NotFound			= "Pas de données disponibles"
	InternalServerError	= "Erreur interne du serveur"
	NotImplemented		= "Commande pas encore impantée"

[fr.frontend]
	dateFrom			= "De"
	dateTo				= "À"
	maximum				= "Max"
	albums				= "Albums"
	tags				= "Étiquettes"
#	images				= "Images"
	HTMLError			= "Erreur HTML"
	InvalidDate			= "Format de date/heure invalide. Ignorée"
	UnknownData			= "Données pas reconnues"
	NoData				= "Pas de données reçues"

[en]
[en.backend]
	Welcome				= "Welcome to"
	Server				= "Server"
	Database			= "Database"
	Unauthorized		= "Command not allowed"
	Forbidden			= "Invalid user or password"
	NotFound			= "No data available"
	InternalServerError	= "Server internal error"
	NotImplemented		= "Command not implemented"

[en.frontend]
	dateFrom			= "From"
	dateTo				= "To"
	maximum				= "Max"
	albums				= "Albums"
	tags				= "Tags"
#	images				= "Images"
	HTMLError			= "HTML error"
	InvalidDate			= "Invalid date/hour format. Ignored"
	UnknownData			= "Unknown data"
	NoData				= "No data received"
	